# Generated by Django 2.2.24 on 2021-12-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha',
        ),
    ]
