# Generated by Django 2.2.24 on 2021-12-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0002_remove_categoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente_informacion',
            name='idConfiguracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Configuracion_Fuente_Informacion'),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='idContenido_Original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Contenido_Original'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idFuente_Informacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Fuente_Informacion'),
        ),
    ]
