# Generated by Django 2.2.24 on 2021-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0003_auto_20211202_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='idConfiguracion',
        ),
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='idContenido_Original',
        ),
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='idFuente_Informacion',
        ),
    ]
