# Generated by Django 2.2.24 on 2021-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0004_auto_20211215_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
