# Generated by Django 2.2.24 on 2021-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0005_fuente_informacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
