# Generated by Django 2.2.24 on 2021-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0006_fuente_informacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default='2021/12/12'),
        ),
    ]
