# Generated by Django 2.2.24 on 2021-12-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0007_fuente_informacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default='12/12/2021'),
        ),
    ]
