# Generated by Django 2.2.24 on 2021-12-16 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0008_auto_20211216_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
