# Generated by Django 2.2.24 on 2021-12-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0009_auto_20211216_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='fecha',
        ),
    ]
