# Generated by Django 2.2.24 on 2021-12-16 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0010_remove_fuente_informacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
