# Generated by Django 2.2.24 on 2021-12-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0012_remove_fuente_informacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='idContenido_Original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Contenido_Original'),
        ),
    ]
