# Generated by Django 2.2.24 on 2021-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0013_fuente_informacion_idcontenido_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente_informacion',
            name='idContenido_Original',
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='URL',
            field=models.URLField(blank=None),
        ),
        migrations.AlterField(
            model_name='fuente_informacion',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
