# Generated by Django 2.2.24 on 2021-12-17 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0014_auto_20211217_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente_informacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
