# Generated by Django 2.2.24 on 2021-12-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0016_remove_fuente_informacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido_procesado',
            name='anotacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='contenido',
            field=models.FileField(upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='fecha_Creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='idAdjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Adjunto'),
        ),
        migrations.AlterField(
            model_name='contenido_procesado',
            name='idContenido_Original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_RDNA.Contenido_Original'),
        ),
    ]
