# Generated by Django 2.2.24 on 2021-12-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_RDNA', '0018_remove_contenido_procesado_idadjunto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adjunto',
        ),
    ]
